# Build stage
FROM docker-pluk-common.pruregistry.intranet.asia:8443/openjdk:21-jdk-slim as build
WORKDIR /app
COPY . .
RUN chmod +x ./pre-build.sh
RUN chmod +x ./gradlew
RUN ./pre-build.sh reset
RUN ./gradlew build --no-daemon
RUN ls -l ./build/libs && echo 1

# Production stage
FROM docker-pluk-common.pruregistry.intranet.asia:8443/tomcat:10.1.44-jdk21

# Environment variables
ENV TOMCAT_HOME=/usr/local/tomcat

# Ensure APT uses HTTPS
RUN sed -i 's|http://|https://|g' /etc/apt/sources.list && \
    find /etc/apt/sources.list.d -type f -exec sed -i 's|http://|https://|g' {} +

# Force update all packages to latest security versions
RUN apt-get update && \
    apt-get install -y --only-upgrade \
    dpkg \
    unzip \
    telnet \
    gnupg \
    apt-transport-https \
    libsystemd0 \
    libudev1 \
    libssh-4 \
    libgnutls30t64 \
    systemd \
    sqlite3 \
    libsqlite3-0 \
    curl=8.5.0-2ubuntu10.6 \
    libcurl4t64=8.5.0-2ubuntu10.6 \
    openssl=3.0.13-0ubuntu3.6 \
    libssl3t64=3.0.13-0ubuntu3.6 \
    libpam0g=1.5.3-5ubuntu5.5 \
    libpam-modules-bin=1.5.3-5ubuntu5.5 \
    libpam-modules=1.5.3-5ubuntu5.5 \
    libpam-runtime=1.5.3-5ubuntu5.5 \
    locales=2.39-0ubuntu8.6 \
    libc6=2.39-0ubuntu8.6 \
    libc-bin=2.39-0ubuntu8.6 \
    libexpat1=2.6.1-2ubuntu0.3 \
    expat=2.6.1-2ubuntu0.3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install MSSQL Tools (Debian 12 repo works for Ubuntu 24.04)
RUN set -eux; \
   mkdir -p /etc/apt/keyrings; \
   curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
       | gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg; \
   echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
> /etc/apt/sources.list.d/mssql-release.list; \
   apt-get update; \
   ACCEPT_EULA=Y apt-get install -y --no-install-recommends mssql-tools; \
   ln -s /opt/mssql-tools/bin/sqlcmd /usr/local/bin/sqlcmd; \
   apt-get clean; \
   rm -rf /var/lib/apt/lists/*

# Copy build artifacts from the build stage
COPY --from=build /app/fish-startup.sh $TOMCAT_HOME/bin/fish-startup.sh
COPY --from=build /app/test-api.sh $TOMCAT_HOME/bin/test-api.sh
COPY --from=build /app/run-mssql-scripts.sh $TOMCAT_HOME/bin/run-mssql-scripts.sh
COPY --from=build /app/database/ $TOMCAT_HOME/bin/database/
COPY --from=build /app/tomcat/ $TOMCAT_HOME/conf/
COPY --from=build /app/build/libs/*.war $TOMCAT_HOME/webapps/fish.war

# Prepare Tomcat
RUN mkdir $TOMCAT_HOME/cmd
RUN chmod +x $TOMCAT_HOME/bin/*.sh

# Webapp startup
CMD ["fish-startup.sh"]
EXPOSE 8080

#test deployment
